### PR TITLE
Document & test the semantics of `GetRawTransaction`, and fix platform-dependent parsing.

### LINKED ISSUE #493: `GetTransaction` does not correctly propagate the output of `getrawtransaction` calls.
It turns out that the `GetTransaction` method added to `lightwalletd` is horribly broken, because it does not correctly propagate the output of the `getrawtransaction` JSON-RPC method.

It says here "optionally includes the block height" (which runs into the gRPC problem that this gets aliased with the genesis block height 0 making the transactions look mined), but below says "block height if mined, or -1" (implying to users of the RPC that -1 means "unmined").

Meanwhile, `getrawtransaction` actually returns:
- A non-negative height for transactions mined in blocks in the current main chain.
- `-1` for transactions mined in blocks that are not in the main chain (i.e. conflicted).
- Omitted for unmined transactions in the mempool.

This is further muddied by the fact that the Go parser is parsing the height field as an `int`, which is machine-dependent (and thus could differ from `zcashd`), and also I don't know how it handles omitted values (because it isn't to my knowledge a nullable type). So the unmined transactions might be getting their height fields coerced to some default in Go (0?) rather than being set as optional in the returned Protobuf (aka 0) - this needs further investigation.

`RawTransaction` was then further misused by the addition of the `GetMempoolStream` RPC. Transactions in the mempool should **never** be associated with the latest block height; if any height is associated with them, it should be the "mempool height" which is `latest_height + 1` (which is the height at which the consensus rules are applied to the mempool transactions). So that RPC is broken as well.

This is going to be Not Fun™️ to fix.

_Originally posted by @str4d in https://github.com/zcash/librustzcash/pull/1473#discussion_r1701063435_

### PR DESCRIPTION
**Pull request by nuttycom**
Please ensure this checklist is followed for any pull requests for this repo. This checklist must be checked by both the PR creator and by anyone who reviews the PR.
* [ ] Relevant documentation for this PR has to be completed before the PR can be merged
* [x] A test plan for the PR must be documented in the PR notes and included in the test plan for the next regular release

As a note, all CI tests need to be passing and all appropriate code reviews need to be done before this PR can be merged

Fixes #493

### CODE REVIEW

File: frontend/service.go [hunk 1]
```diff
@@ -307,6 +307,43 @@ func (s *lwdStreamer) GetLatestTreeState(ctx context.Context, in *walletrpc.Empt
...
+// return the int64 value `-1` for the height of transactions that appear in
+// the block index, but which are not mined in the main chain. `service.proto`
+// defines the height field of `RawTransaction` to be a `uint64`, and as such
+// we must map the response from the zcashd RPC API to be representable within
+// this space. Additionally, the `height` field will be absent for transactions
+// in the mempool, resulting in the default value of `0` being set. Therefore,
+// the meanings of the `Height` field of the `RawTransaction` type are as
+// follows:
+//
+// * height 0: the transaction is in the mempool
```
Comment (str4d) [inline frontend/service.go:324]: This aliases with the genesis block height, but is safe solely because the mainnet Zcash genesis block only contained a single transaction (the coinbase) which had no outputs (due to slow start), so no wallet will ever be interested in it even if they incorrectly observe it as "in the mempool".

File: walletrpc/service.proto [hunk 2]
```diff
@@ -31,12 +31,31 @@ message TxFilter {
      bytes hash = 3;        // transaction ID (hash, txid)
 }
 
-// RawTransaction contains the complete transaction data. It also optionally includes 
-// the block height in which the transaction was included, or, when returned
-// by GetMempoolStream(), the latest block height.
```
Comment (str4d) [inline walletrpc/service.proto:36]: Bug: you're removing the documentation about its use in `GetMempoolStream` without either removing this usage from there, or fixing the bug that exists in `GetMempoolStream` (that it returns the chain tip height).

If we want consistency of how `RawTransaction` is used between `GetTransaction` and `GetMempoolStream`, we'd need to return `height = 0` (as sentinel for "in the mempool") from `GetMempoolStream`. However, given that downstream users currently expect `GetMempoolStream` to always return a height and would probably break badly if they got the genesis height, we should probably instead return the sentinel "chain tip height + 1" as the "mempool height". If we do this latter approach, then if we're still using `RawTransaction` (as we probably need to for protobuf compatibility) we will need to update this documentation to record the distinction.

**Review by str4d — CHANGES_REQUESTED** [review]
Reviewed d17baf7dbc31bf913765efe9a25bc2e1dbf34140.

File: walletrpc/service.proto (hunk 2 above)
Comment (nuttycom) [reply walletrpc/service.proto:36]: As we discussed, Zingo is currently the only project that is known to be using this height value, and they will update their usage. As such, I think that `chain_tip + 1` is not a suitable value for representing the mempool height, because the consumer of `RawTransaction` has no way to distinguish whether a returned transaction is in the mempool or has actually been mined; they would need to know how that `RawTransaction` value was retrieved, and pass that context along. As such, I will add a commit that fixes the `GetMempoolStream` behavior to return `0` for transactions in the mempool.

Comment (str4d) [reply walletrpc/service.proto:36]: Yeah, that is probably the safest change to make overall. It does however mean that there is a potential race condition where:
- Caller has no open `GetMempoolStream`.
- Caller checks the chain tip height.
- Chain tip height changes (in any direction), stopping any _existing_ `GetMempoolStream`
- Caller starts a _new_ `GetMempoolStream`

and the caller will think the mempool is associated with a target height that it is not.

Comment (str4d) [reply walletrpc/service.proto:36]: The core issue is that `GetMempoolStream` is not a great API (in particular because it streams the entire mempool from scratch as each block comes in), and we should plan to replace it with a better API (that provides a mempool diff along with the height transition associated with it).

Comment (nuttycom) [reply walletrpc/service.proto:36]: Fixed in b5f3f6348df4f6f4a2690a8f8806c571557fe642

File: common/mempool.go [hunk 3]
```diff
@@ -105,35 +104,27 @@ func refreshMempoolTxns() error {
...
+		g_txidSeen[txid(txidstr)] = struct{}{}
 		txidJSON, err := json.Marshal(txidstr)
 		if err != nil {
 			return err
 		}
-		// The "0" is because we only need the raw hex, which is returned as
-		// just a hex string, and not even a json string (with quotes).
-		params := []json.RawMessage{txidJSON, json.RawMessage("0")}
+
+		params := []json.RawMessage{txidJSON, json.RawMessage("1")}
```
Comment (str4d) [inline common/mempool.go:115]: An interesting side effect of this (using verbose `getrawtransaction`) is that if we get the list of mempool transactions, and then a new block arrives before we finish sending them, any transactions that got mined will have height set to their mined height instead of 0 (and then once all the new "mempool" txs are sent, the stream will end as the server detects the new block).

**Review by str4d — APPROVED** [review]
utACK b5f3f6348df4f6f4a2690a8f8806c571557fe642 with note about how `GetMempool*` will not uniformly return 0. It would be nice to apply the moves from the last commit to the earlier commits in which the moved content was added.

File: CHANGELOG.md [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
+and this library adheres to Rust's notion of
+[Semantic Versioning](https://semver.org/spec/v2.0.0.html).
+
+## [Unreleased]
+
+### Changed
+
+- The `RawTransaction` values returned from a call to `GetMempoolStream`
+  now report a `Height` value of `0`, in order to be consistent with
```
Comment (str4d) [inline CHANGELOG.md:13]: Not entirely true given my previous observation.

**Review by str4d — APPROVED** [review]
Re-utACK 56fe52a11a1c1e2dad2af62e471a76b9de31d376

File: common/mempool.go (hunk 3 above)
Comment (LarryRuane) [reply common/mempool.go:115]: Good point, @str4d. Also, if the returned transaction has a nonzero height, it would be best to filter it out since we know it's no longer in the mempool (we must have hit this timing window).

**Review by str4d — APPROVED** [review]
utACK 90116a7c55256e597c9a86b31ed942aebaf33699

**Review by AArnott — COMMENTED** [review]
The doc changes are clear and good. I don't know Go enough to offer a decent review of them.

**Review by pacu — COMMENTED** [review]
utACK

**Review by LarryRuane — COMMENTED** [review]
post-merge ACK
