### PR TITLE
fix GetLatestBlock gRPC reply block hash endianness

### LINKED ISSUE #512: `GetLatestBlock` hash response has been broken for 2.5 years without anyone noticing
#415 broke the API.

Prior to this, the latest block hash was obtained from the cache, which in turn obtained it from a `CompactBlock`, which in turn obtained its hash from directly hashing a block header:
https://github.com/zcash/lightwalletd/blob/6c400288240615ad4c59e748fd876466553c2e3f/parser/block_header.go#L217-L230

After this change, it decodes the big-endian hex string returned by `getblockchaininfo`, and then fails to byte-reverse it to produce the little-endian byte encoding.

I noticed this because Zaino has reproduced the buggy behaviour in its lightwalletd implementation:
https://github.com/AloeareV/zaino/blob/766d828a3652b34dcd75ad76152fd4648f305bd1/zaino-state/src/fetch.rs#L490-L498

_Originally posted by @str4d in https://github.com/zcash/lightwalletd/pull/415#discussion_r2026765955_

### PR DESCRIPTION
**Pull request by LarryRuane**
Closes #512
Return the hash of the latest block in little-endian order, rather than big-endian. This hash is a byte array, not a hex string, so it should be in little-endian format. It does not appear that anyone is depending on this fix at the moment (no one is using the hash result of this gRPC).

### CODE REVIEW

**Comment by LarryRuane** [comment]
I manually tested this as follows. On zcashd (mainnet):
```
$ src/zcash-cli getblockchaininfo |jq '.blocks,.bestblockhash'
2876918
"0000000000569becaac78b6bfb58ffc516922e64dff8c24da1599f2cfa6fe174"
```
On lightwalletd (with this PR):
```
$ grpcurl -plaintext localhost:9067 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestBlock
{
  "height": "2876918",
  "hash": "dOFv+iyfWaFNwvjfZC6SFsX/WPtri8eq7JtWAAAAAAA="
}
$ base642hex dOFv+iyfWaFNwvjfZC6SFsX/WPtri8eq7JtWAAAAAAA=
74e16ffa2c9f59a14dc2f8df642e9216c5ff58fb6b8bc7aaec9b560000000000
```
Without this PR, the hash string starts with the zeros (which means it's big-endian).

Note,  `base642hex` is this little script:
```
#!/usr/bin/env python3
import sys 
import codecs
for x in sys.argv[1:]:
    print(codecs.encode(codecs.decode(bytes(x, 'ascii'), 'base64'), 'hex').decode())
```

File: frontend/service.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ func (s *lwdStreamer) GetLatestBlock(ctx context.Context, placeholder *walletrpc
 	if err != nil {
 		return nil, err
 	}
-	r := &walletrpc.BlockID{Height: uint64(blockChainInfo.Blocks), Hash: []byte(bestBlockHash)}
+	r := &walletrpc.BlockID{Height: uint64(blockChainInfo.Blocks), Hash: parser.Reverse(bestBlockHash)}
```
Comment (str4d) [inline frontend/service.go:75]: Document this bugfix in the changelog (which looks like it hasn't been updated for a while, but this is an important bugfix for people to be aware of; make any other changes necessary to delineate this fix from the prior changes).

I would also prefer that `bestBlockHash` be in little-endian encoding, i.e. we do not store the hex-decoded-but-not-reversed bytes in a variable (otherwise we run the risk of encountering this exact same bug again in some future refactor). So either move the `parser.Reverse` up to wrap `bestBlockHash` in some way, or inline the `hex.DecodeString` here.

**Review by str4d — CHANGES_REQUESTED** [review]

**Review by str4d — APPROVED** [review]
utACK 17533b6f75c624dabe0abc5d2ffb6e3a4f98cfe0
