### PR TITLE
Fix V5 transaction txid (#392)

### LINKED ISSUE #392: Implement ZIP 244 txid logic for v5 transactions
Support for parsing v5 transactions (as specified in ZIP 225) was added in #367. However, the txid computation for v5 transactions (as specified in ZIP 244) was not implemented. This means that at present, `lightwalletd` returns incorrect txids for v5 transactions in compact blocks:

https://github.com/zcash/lightwalletd/blob/ab4c0fef70dcb195f131d3d794e0c9cec2972dba/common/common.go#L261-L274

https://github.com/zcash/lightwalletd/blob/ab4c0fef70dcb195f131d3d794e0c9cec2972dba/parser/block.go#L108-L127

https://github.com/zcash/lightwalletd/blob/ab4c0fef70dcb195f131d3d794e0c9cec2972dba/parser/transaction.go#L379-L383

https://github.com/zcash/lightwalletd/blob/ab4c0fef70dcb195f131d3d794e0c9cec2972dba/parser/transaction.go#L346-L365

### PR DESCRIPTION
**Pull request by LarryRuane**
Partially fixes #392 
This is a shortcut fix. Instead of replicating the zip244 transaction
logic that's implemented in librustzcash:
zcash_primitives/src/transaction/components/orchard.rs

cheat by calling getblock with verbose level 1, which prints the txid
of each transaction. This currently requires calling getblock twice,
once for the raw hex (as we have always done), and again to get the
transaction IDs. An easy improvement would be to add the raw hex to
verbosity 1 result. (Or have a new verbosity that shows both.)

The unit tests don't pass with this change, but I wanted to make it
available for testing as soon as possible, we can fix the tests later.

### CODE REVIEW

**Comment by str4d** [comment]
> An easy improvement would be to add the raw hex to
verbosity 1 result.

We will not do this; it could greatly increase the size of `verbosity = 1` RPC outputs, which could have negative performance effects on downstream users.

File: common/common.go [hunk 1]
```diff
@@ -271,6 +276,31 @@ func getBlockFromRPC(height int) (*walletrpc.CompactBlock, error) {
 		return nil, errors.New("received unexpected height block")
 	}
 
+	// Get the txids; it would be more efficient to implement a
+	// getblock verbose level that returns both raw hex and the txid list
+	// so that this second rpc wouldn't be needed.
```
Comment (str4d) [inline common/common.go:281]: This comment doesn't explain why this is necessary, which is that `block.ParseFromSlice` is broken for blocks containing v5 transactions.
```suggestion
	// `block.ParseFromSlice` correctly parses blocks containing v5 transactions, but
	// incorrectly computes the IDs of the v5 transactions. We temporarily paper over this
	// bug by fetching the correct txids via a second getblock RPC call.
	// https://github.com/zcash/lightwalletd/issues/392
```

File: common/common.go [hunk 2]
```diff
@@ -271,6 +276,31 @@ func getBlockFromRPC(height int) (*walletrpc.CompactBlock, error) {
...
+	{
+		params[0] = heightJSON
```
Comment (str4d) [inline common/common.go:283]: We don't need this line.
```suggestion
```

File: common/common.go [hunk 3]
```diff
@@ -271,6 +276,31 @@ func getBlockFromRPC(height int) (*walletrpc.CompactBlock, error) {
...
+		params[1] = json.RawMessage("1") // non-verbose (raw hex)
```
Comment (str4d) [inline common/common.go:284]:
```suggestion
		params[1] = json.RawMessage("1") // verbose (JSON with list of txids)
```

File: parser/transaction.go [hunk 4]
```diff
@@ -339,29 +338,23 @@ func (p *action) ToCompact() *walletrpc.CompactOrchardAction {
...
-	return tx.cachedTxID
+	return Reverse(tx.txID[:])
 }
 
 // GetEncodableHash returns the transaction hash in little-endian wire format order.
 func (tx *Transaction) GetEncodableHash() []byte {
-	digest := sha256.Sum256(tx.rawBytes)
-	digest = sha256.Sum256(digest[:])
-	return digest[:]
+	return tx.txID
```
Comment (str4d) [inline parser/transaction.go:357]: This remains a bug, because if the caller doesn't call `SetTxID` then this returns the empty array. But it's a more visible bug than before, so I'm okay with removing the v4 txid derivation logic for now, and then re-introducing it when #392 is fixed.

File: parser/transaction_test.go [hunk 5]
```diff
@@ -85,9 +84,8 @@ func TestV5TransactionParser(t *testing.T) {
 		if len(rest) != 0 {
 			t.Fatalf("Test did not consume entire buffer, %d remaining", len(rest))
 		}
-		if bytes.Equal(tx.cachedTxID, []byte(txtestdata.Txid)) {
-			t.Fatal("txid")
-		}
+		// Currently, we can't check the txid because we get that from
+		// zcashd (getblock rpc) rather than computing it ourselves.
```
Comment (str4d) [inline parser/transaction_test.go:88]: Add an issue reference here so we remember to re-add this test when fixing the issue:
```suggestion
		// Currently, we can't check the txid because we get that from
		// zcashd (getblock rpc) rather than computing it ourselves.
		// https://github.com/zcash/lightwalletd/issues/392
```

**Review by str4d — CHANGES_REQUESTED** [review]
Code changes LGTM, but I have not tested them.

**Comment by LarryRuane** [comment]
> > An easy improvement would be to add the raw hex to
> > verbosity 1 result.
> 
> We will not do this; it could greatly increase the size of `verbosity = 1` RPC outputs, which could have negative performance effects on downstream users.

Verbosity should be a bitfield.

File: common/common.go (hunk 3 above)
Comment (LarryRuane) [reply common/common.go:284]: I hate copy and paste :)

**Comment by LarryRuane** [comment]
Force-pushed to address review comments, thanks str4d!

File: common/common.go (hunk 1 above)
Comment (str4d) [reply common/common.go:281]: This comment still needs rewriting, at a minimum to reference the open issue, but ideally saying that this second fetch is necessary because `block.ParseFromSlice` doesn't yet implement txid derivation.

**Comment by str4d** [comment]
> Verbosity should be a bitfield.

Perhaps, but we'd need to be careful about how this interacts with upstream, since `getblock` _will_ be assumed by the wider community to behave like Bitcoin Core does.

**Comment by LarryRuane** [comment]
One more force-push to fix a comment as suggested by @str4d
