### PR TITLE
return correct gRPC error codes

### LINKED ISSUE #497: Zcash rpc error codes are not being correctly mapped to GRPC responses.
**What is the bug?**
`lightwalletd` appears to be directly propagating RPC errors from `zcashd` and `zebra`, instead of reinterpreting them as the correct GRPC error types.

Here is an example of a `grpcurl` session:
```
~/work/lightwalletd on ᚠfix/get_transaction_notfound [$] via 🐹 v1.22.2 on ☁️   googleplay@z.cash(us-east1)
✗ grpcurl -d @ na-lax.zcashd.zec.rocks:443 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTransaction <<EOM
{"hash": "OVmYYbd17odbutVyi9YaHZqAbyBzixVG6q/wTdwgEFM="}
EOM
ERROR:
  Code: Unknown
  Message: -5: No such mempool or blockchain transaction. Use gettransaction for wallet transactions.

~/work/lightwalletd on ᚠfix/get_transaction_notfound [$] via 🐹 v1.22.2 on ☁️   googleplay@z.cash(us-east1)
✗ grpcurl -d @ zec.rocks:443 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTransaction <<EOM
{"hash": "OVmYYbd17odbutVyi9YaHZqAbyBzixVG6q/wTdwgEFM="}
EOM
ERROR:
  Code: Unknown
  Message: 0: Transaction not found
```
In both cases, the error being returned should actually be code `5: NotFound`, as described in https://github.com/grpc/grpc/blob/master/doc/statuscodes.md#status-codes-and-their-use-in-grpc

In general, the error codes from zcashd rpc methods should be interrogated and mapped to the corresponding GRPC error codes when possible; `2: Unknown` should be used only as a last resort.

### PR DESCRIPTION
**Pull request by LarryRuane**
closes #497

### CODE REVIEW

**Comment by LarryRuane** [comment]
This PR includes some whitespace changes to common/common_test.go because my IDE (vscode) automatically formats files, and an earlier commit to this file used a different formatting convention. I recommend viewing the diff with whitespace ignored (click on the gear symbol near the top of the Files changed (diff) page).

File: common/common.go [hunk 1]
```diff
@@ -311,15 +318,13 @@ func getBlockFromRPC(height int) (*walletrpc.CompactBlock, error) {
...
 	// both the list of txids, which we're not yet able to compute for
 	// Orchard (V5) transactions, and the block hash (block ID), which
 	// we need to fetch the raw data format of the same block. Don't fetch
 	// by height in case a reorg occurs between the two getblock calls;
 	// using block hash ensures that we're fetching the same block.
-	params[1] = json.RawMessage("1")
+	params := []json.RawMessage{heightJSON, json.RawMessage("1")}
 	result, rpcErr := RawRequest("getblock", params)
 	if rpcErr != nil {
 		// Check to see if we are requesting a height the zcashd doesn't have yet
```
Comment (upbqdn) [inline common/common.go:330]: Shouldn't the checked code be `-5`? 

References: 

- https://github.com/zcash/zcash/blob/99ad6fdc3a549ab510422820eea5e5ce9f60a5fd/src/rpc/blockchain.cpp#L833-L834 
- https://github.com/zcash/zcash/blob/99ad6fdc3a549ab510422820eea5e5ce9f60a5fd/src/rpc/protocol.h#L46.

Comment (conradoplg) [reply common/common.go:330]: It's -5 for hashes but -8 for heights. What is weird is the comment above mentioning that it should be a hash but it is not. That's not part of the PR though.

**Comment by LarryRuane** [comment]
Part of this patch (the small change to `cmd/root.go`) requires https://github.com/zcash/zcash/pull/6972 to be effective (not be a no-op), but this PR can be merged without (or before) 6972 is merged; there is no harm in doing so.

**Comment by LarryRuane** [comment]
Rebased to fix merge conflicts, I believe this is ready to merge and it is safe, hoping for more review (thanks for your review, @y4ssi).

**Comment by LarryRuane** [comment]
Here's an example of the difference in the error returns. Start a `lightwalletd` instance on mainnet, then try to fetch a non-existent transaction (but the length of the txid is valid, 64 bytes):
```
$ grpcurl -plaintext -d '{"hash":"OVmYYbd17odbutVyi9YaHZqAbyBzixVG6q/wTdwgEFM="}' localhost:9067 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTransaction
```
Without this PR, this is the output:
```
ERROR:
  Code: Unknown
  Message: -5: No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
```
With this PR:
```
ERROR:
  Code: NotFound
  Message: GetTransaction: getrawtransaction 531020dc4df0afea46158b73206f809a1d1ad68b72d5ba5b87ee75b761985939 failed: -5: No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
```
Here's another example, requesting a block that doesn't exist, height is too large (returns `OutOfRange` instead of `Unknown`):
```
$ grpcurl -plaintext -d '{"height":3640508}' localhost:9067 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlock
ERROR:
  Code: OutOfRange
  Message: GetBlock: block 3640508 is newer than the latest block
```

**Comment by LarryRuane** [comment]
force-pushed to make two small formatting improvements

**Comment by LarryRuane** [comment]
The latest (force) push was to rebase, and also remove the changes that were to go along with https://github.com/zcash/zcash/pull/6972 but we decided not to do these changes, at least for now.
