### PR TITLE
fix GetLatestBlock() gRPC (pure block cache)

### LINKED ISSUE #397: Make the compact block cache a pure cache (its only effect is to improve performance)
Currently, lightwalletd's compact block cache is more than just a cache. In some ways it does (correctly) act as a pure cache, for example, a `GetBlock` request for a block that's not yet in the cache will immediately forward the request to `zcashd` and return the expected data. (It will not say that the block is not found.)

But in other ways, the existence of the cache shows through the gRPC interface. For example, while lightwalletd is syncing, I ran this gRPC twice a few seconds apart:
```
$ grpcurl -plaintext localhost:9067 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestBlock
{
  "height": "1888972",
  "hash": "lYVKq/FeWuwn/78DD+PPC3Yh4TVAraXUUo0aQ9srBQA="
}
$ grpcurl -plaintext localhost:9067 cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestBlock
{
  "height": "1889588",
  "hash": "+LknCZEcn9ZmNUfsKxQlDAulqoAN16dlMvs0KCTbGgA="
}
$ 
```
It's showing the current height of the cache (which is changing quickly, the reported heights differ by about 600). Instead, lightwalletd should really recognize that it's syncing, and query its `zcashd` to get _its_ idea of the latest block.

There may be other gRPCs that would need to be updated to fully implement this idea.

This relates to #170, but that one involves `zcashd` itself syncing. That's very rare, and whoever is running the lightwalletd server can always (and should always) simply wait until `zcashd` is fully synced before starting `lightwalletd`. I think this issue here is more important to fix, because once `lightwalletd` starts, it provides service, _even if_ its cache is still syncing. I guess another way to solve this would be for lightwalletd to not advertise its service until its cache is synced. But it would be better to provide service as soon as possible.

### PR DESCRIPTION
**Pull request by LarryRuane**
Fixes #397. If the block cache is still populating (lightwalletd is syncing with zcashd), behave the same as if the cache was fully populated, other than performance.

This turned out to affect only the GetLatestBlock() gRPC. Previously, it would return the height and hash of the latest block in the cache. After this commit, it queries zcashd using the getblockchaininfo, which contains both of those values.

The only possible downside to this change is if the client calls `GetLatestBlock()` very frequently; with this change, each call requires an RPC to `zcashd`. But even a frequency of, say, once per second would be completely fine, and there's no reason it would be called more frequently than that (general range).

GetBlock() (and GetBlockRange()) already worked correctly; if the requested block isn't in the cache, it requests it from zcashd.

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK

**Review by pacu — APPROVED** [review]
utACK

File: frontend/service.go [hunk 1]
```diff
@@ -62,14 +62,15 @@ func (s *lwdStreamer) GetLatestBlock(ctx context.Context, placeholder *walletrpc
...
+		return nil, err
 	}
-	latestHash := s.cache.GetLatestHash()
-
-	return &walletrpc.BlockID{Height: uint64(latestBlock), Hash: latestHash}, nil
+	bestBlockHash, err := hex.DecodeString(blockChainInfo.BestBlockHash)
+	if err != nil {
+		return nil, err
+	}
+	return &walletrpc.BlockID{Height: uint64(blockChainInfo.Blocks), Hash: []byte(bestBlockHash)}, nil
```
Comment (str4d) [inline frontend/service.go:73]: This broke the API.

Prior to this, the latest block hash was obtained from the cache, which in turn obtained it from a `CompactBlock`, which in turn obtained its hash from directly hashing a block header:
https://github.com/zcash/lightwalletd/blob/6c400288240615ad4c59e748fd876466553c2e3f/parser/block_header.go#L217-L230

After this change, it decodes the big-endian hex string returned by `getblockchaininfo`, and then fails to byte-reverse it to produce the little-endian byte encoding.

I noticed this because Zaino has reproduced the buggy behaviour in its lightwalletd implementation:
https://github.com/AloeareV/zaino/blob/766d828a3652b34dcd75ad76152fd4648f305bd1/zaino-state/src/fetch.rs#L490-L498
